spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database1
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false